class PlanetModel {
  final String name;
  final String image;
  final String description;

  PlanetModel({required this.name, required this.image, required this.description});

  static List<PlanetModel> planets = [
    PlanetModel(name: "Earth", image: "Assets/earth1.png", description: "About\nEarth is the only known planet in the universe that supports life. Its unique combination of factors, including liquid water, a breathable atmosphere, and a suitable distance from the Sun, has created the ideal conditions for the development of complex organisms. Earth's magnetic field protects it from harmful solar radiation, and its atmosphere helps to regulate temperature and weather patterns.\n\nDistance from Sun (km) : 149598026\nLength of Day (hours) : 23.93\nOrbital Period (Earth years) : 1\nRadius (km) : 6371\nMass (kg) : 5.972 × 10²⁴\nGravity (m/s²) : 9.81\nSurface Area (km²) : 5.10 × 10⁸"),
    PlanetModel(name: "Jupiter", image: "Assets/jupiter.png", description: "About\nplanet is the only known planet in the universe that supports life. Its unique combination of factors, including liquid water, a breathable atmosphere, and a suitable distance from the Sun, has created the ideal conditions for the development of complex organisms. Earth's magnetic field protects it from harmful solar radiation, and its atmosphere helps to regulate temperature and weather patterns.\n\nDistance from Sun (km) : 149598026\nLength of Day (hours) : 23.93\nOrbital Period (Earth years) : 1\nRadius (km) : 6371\nMass (kg) : 5.972 × 10²⁴\nGravity (m/s²) : 9.81\nSurface Area (km²) : 5.10 × 10⁸"),
    PlanetModel(name: "Mars", image: "Assets/mars.png", description: "About\nplanet is the only known planet in the universe that supports life. Its unique combination of factors, including liquid water, a breathable atmosphere, and a suitable distance from the Sun, has created the ideal conditions for the development of complex organisms. Earth's magnetic field protects it from harmful solar radiation, and its atmosphere helps to regulate temperature and weather patterns.\n\nDistance from Sun (km) : 149598026\nLength of Day (hours) : 23.93\nOrbital Period (Earth years) : 1\nRadius (km) : 6371\nMass (kg) : 5.972 × 10²⁴\nGravity (m/s²) : 9.81\nSurface Area (km²) : 5.10 × 10⁸"),
    PlanetModel(name: "Mercury", image: "Assets/mercury.png", description: "About\nplanet is the only known planet in the universe that supports life. Its unique combination of factors, including liquid water, a breathable atmosphere, and a suitable distance from the Sun, has created the ideal conditions for the development of complex organisms. Earth's magnetic field protects it from harmful solar radiation, and its atmosphere helps to regulate temperature and weather patterns.\n\nDistance from Sun (km) : 149598026\nLength of Day (hours) : 23.93\nOrbital Period (Earth years) : 1\nRadius (km) : 6371\nMass (kg) : 5.972 × 10²⁴\nGravity (m/s²) : 9.81\nSurface Area (km²) : 5.10 × 10⁸"),
    PlanetModel(name: "Neptune", image: "Assets/neptune.png", description: "About\nplanet is the only known planet in the universe that supports life. Its unique combination of factors, including liquid water, a breathable atmosphere, and a suitable distance from the Sun, has created the ideal conditions for the development of complex organisms. Earth's magnetic field protects it from harmful solar radiation, and its atmosphere helps to regulate temperature and weather patterns.\n\nDistance from Sun (km) : 149598026\nLength of Day (hours) : 23.93\nOrbital Period (Earth years) : 1\nRadius (km) : 6371\nMass (kg) : 5.972 × 10²⁴\nGravity (m/s²) : 9.81\nSurface Area (km²) : 5.10 × 10⁸"),
    PlanetModel(name: "Saturn", image: "Assets/saturn.png", description: "About\nplanet is the only known planet in the universe that supports life. Its unique combination of factors, including liquid water, a breathable atmosphere, and a suitable distance from the Sun, has created the ideal conditions for the development of complex organisms. Earth's magnetic field protects it from harmful solar radiation, and its atmosphere helps to regulate temperature and weather patterns.\n\nDistance from Sun (km) : 149598026\nLength of Day (hours) : 23.93\nOrbital Period (Earth years) : 1\nRadius (km) : 6371\nMass (kg) : 5.972 × 10²⁴\nGravity (m/s²) : 9.81\nSurface Area (km²) : 5.10 × 10⁸"),
    PlanetModel(name: "Uranus", image: "Assets/uranus.png", description: "About\nplanet is the only known planet in the universe that supports life. Its unique combination of factors, including liquid water, a breathable atmosphere, and a suitable distance from the Sun, has created the ideal conditions for the development of complex organisms. Earth's magnetic field protects it from harmful solar radiation, and its atmosphere helps to regulate temperature and weather patterns.\n\nDistance from Sun (km) : 149598026\nLength of Day (hours) : 23.93\nOrbital Period (Earth years) : 1\nRadius (km) : 6371\nMass (kg) : 5.972 × 10²⁴\nGravity (m/s²) : 9.81\nSurface Area (km²) : 5.10 × 10⁸"),
    PlanetModel(name: "Venus", image: "Assets/venus.png", description: "About\nplanet is the only known planet in the universe that supports life. Its unique combination of factors, including liquid water, a breathable atmosphere, and a suitable distance from the Sun, has created the ideal conditions for the development of complex organisms. Earth's magnetic field protects it from harmful solar radiation, and its atmosphere helps to regulate temperature and weather patterns.\n\nDistance from Sun (km) : 149598026\nLength of Day (hours) : 23.93\nOrbital Period (Earth years) : 1\nRadius (km) : 6371\nMass (kg) : 5.972 × 10²⁴\nGravity (m/s²) : 9.81\nSurface Area (km²) : 5.10 × 10⁸"),
    PlanetModel(name: "Sun", image: "Assets/sun.png", description: "About\nplanet is the only known planet in the universe that supports life. Its unique combination of factors, including liquid water, a breathable atmosphere, and a suitable distance from the Sun, has created the ideal conditions for the development of complex organisms. Earth's magnetic field protects it from harmful solar radiation, and its atmosphere helps to regulate temperature and weather patterns.\n\nDistance from Sun (km) : 149598026\nLength of Day (hours) : 23.93\nOrbital Period (Earth years) : 1\nRadius (km) : 6371\nMass (kg) : 5.972 × 10²⁴\nGravity (m/s²) : 9.81\nSurface Area (km²) : 5.10 × 10⁸"),
  ];
}